/**
 * Build-time helpers for package metadata generation.
 *
 * These functions handle Gro-specific concerns like file collection and dependency
 * graph extraction. Core analysis logic has been extracted to reusable helpers:
 *
 * - `ts_helpers.ts` - `ts_analyze_module_exports`
 * - `svelte_helpers.ts` - `svelte_analyze_file`
 * - `module_helpers.ts` - path utilities and source detection
 *
 * Design philosophy: Fail fast with clear errors rather than silently producing invalid
 * metadata. All validation errors halt the build immediately with actionable messages.
 *
 * @see package.gen.ts for the main generation task
 * @see src_json.ts for type definitions
 * @see ts_helpers.ts for reusable TypeScript analysis
 * @see svelte_helpers.ts for reusable Svelte component analysis
 */

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Logger} from '@ryanatkn/belt/log.js';
import type {Filer} from '@ryanatkn/gro/filer.js';
import type {Disknode} from '@ryanatkn/gro/disknode.js';
import type ts from 'typescript';

import type {Module_Json, Src_Json} from './src_json.js';
import {ts_analyze_module_exports} from './ts_helpers.js';
import {svelte_analyze_file} from './svelte_helpers.js';
import {
	module_extract_path,
	module_is_typescript,
	module_is_svelte,
	module_matches_source,
} from './module_helpers.js';

/**
 * Validates that no identifier names are duplicated across modules.
 * The flat namespace is intentional - duplicates should fail fast.
 *
 * @throws Error if duplicate identifier names are found
 */
export const package_gen_validate_no_duplicates = (src_json: Src_Json, log: Logger): void => {
	const identifier_locations: Map<string, Array<{module: string; kind: string}>> = new Map();

	// Collect all identifier names and their locations
	for (const mod of src_json.modules ?? []) {
		for (const identifier of mod.identifiers ?? []) {
			const name = identifier.name;
			if (!identifier_locations.has(name)) {
				identifier_locations.set(name, []);
			}
			identifier_locations.get(name)!.push({
				module: mod.path,
				kind: identifier.kind,
			});
		}
	}

	// Check for duplicates
	const duplicates: Array<{name: string; locations: Array<{module: string; kind: string}>}> = [];
	for (const [name, locations] of identifier_locations.entries()) {
		if (locations.length > 1) {
			duplicates.push({name, locations});
		}
	}

	if (duplicates.length > 0) {
		log.error('Duplicate identifier names detected in flat namespace:');
		for (const {name, locations} of duplicates) {
			log.error(`  "${name}" found in:`);
			for (const {module, kind} of locations) {
				log.error(`    - ${module} (${kind})`);
			}
		}
		throw new Error(
			`Found ${duplicates.length} duplicate identifier name${duplicates.length === 1 ? '' : 's'} across modules. ` +
				'The flat namespace requires unique names. Please rename one of the conflicting identifiers. ' +
				'See CLAUDE.md "Identifier namespacing" section for details on this design decision.',
		);
	}
};

/**
 * Sort modules alphabetically by path for deterministic output and cleaner diffs.
 */
export const package_gen_sort_modules = (modules: Array<Module_Json>): Array<Module_Json> => {
	return modules.slice().sort((a, b) => a.path.localeCompare(b.path));
};

/**
 * Generate the package.ts file content with package_json and src_json exports.
 */
export const package_gen_generate_ts = (package_json: Package_Json, src_json: Src_Json): string => {
	const is_this_fuz = package_json.name === '@ryanatkn/fuz';
	return `// Generated by package.gen.ts
// Do not edit directly - regenerated on build

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Src_Json} from '${is_this_fuz ? './src_json.js' : '@ryanatkn/fuz/src_json.js'}';

export const package_json: Package_Json = ${JSON.stringify(package_json, null, '\t')};

export const src_json: Src_Json = ${JSON.stringify(src_json, null, '\t')};
`;
};

/**
 * Collect and filter source files from filer.
 *
 * Returns disknodes for TypeScript/JS files and Svelte components from src/lib, excluding test files.
 *
 * @throws Error if no source files are found in src/lib
 */
export const package_gen_collect_source_files = (filer: Filer, log: Logger): Array<Disknode> => {
	log.info(`filer has ${filer.files.size} files total`);

	const source_disknodes: Array<Disknode> = [];
	for (const [id, disknode] of filer.files.entries()) {
		if (module_matches_source(id)) {
			// Include TypeScript/JS files and Svelte components
			if (module_is_typescript(id) || module_is_svelte(id)) {
				source_disknodes.push(disknode);
			}
		}
	}

	log.info(`found ${source_disknodes.length} source files to analyze`);

	if (source_disknodes.length === 0) {
		throw new Error('No source files found in src/lib - cannot generate package metadata');
	}

	// Sort for deterministic output (stable alphabetical module ordering)
	source_disknodes.sort((a, b) => a.id.localeCompare(b.id));

	return source_disknodes;
};

/**
 * Analyze a Svelte component file and extract metadata.
 *
 * Uses `svelte_analyze_file` for core analysis, then adds
 * Gro-specific dependency information from the disknode.
 */
export const package_gen_analyze_svelte_file = (
	disknode: Disknode,
	module_path: string,
	checker: ts.TypeChecker,
): Module_Json => {
	// Use the extracted helper for core analysis
	const identifier_json = svelte_analyze_file(disknode.id, module_path, checker);

	// Extract dependencies and dependents (Gro-specific)
	const {dependencies, dependents} = package_gen_extract_dependencies(disknode);

	return {
		path: module_path,
		identifiers: [identifier_json],
		dependencies: dependencies.length > 0 ? dependencies : undefined,
		dependents: dependents.length > 0 ? dependents : undefined,
	};
};

/**
 * Analyze a TypeScript file and extract all identifiers.
 *
 * Uses `ts_analyze_module_exports` for core analysis, then adds
 * Gro-specific dependency information from the disknode.
 */
export const package_gen_analyze_typescript_file = (
	disknode: Disknode,
	source_file: ts.SourceFile,
	module_path: string,
	checker: ts.TypeChecker,
): Module_Json => {
	// Use the extracted helper for core analysis
	const {module_comment, identifiers} = ts_analyze_module_exports(source_file, checker);

	const mod: Module_Json = {
		path: module_path,
		identifiers,
	};

	if (module_comment) {
		mod.module_comment = module_comment;
	}

	// Extract dependencies and dependents (Gro-specific)
	const {dependencies, dependents} = package_gen_extract_dependencies(disknode);
	if (dependencies.length > 0) {
		mod.dependencies = dependencies;
	}
	if (dependents.length > 0) {
		mod.dependents = dependents;
	}

	return mod;
};

/**
 * Extract dependencies and dependents for a module from the filer's dependency graph.
 *
 * Filters to only include source modules from src/lib (excludes external packages, node_modules, tests).
 * Returns sorted arrays of module paths (relative to src/lib) for deterministic output.
 */
export const package_gen_extract_dependencies = (
	disknode: Disknode,
): {dependencies: Array<string>; dependents: Array<string>} => {
	const dependencies: Array<string> = [];
	const dependents: Array<string> = [];

	// Extract dependencies (files this module imports)
	for (const dep_id of disknode.dependencies.keys()) {
		if (module_matches_source(dep_id)) {
			dependencies.push(module_extract_path(dep_id));
		}
	}

	// Extract dependents (files that import this module)
	for (const dependent_id of disknode.dependents.keys()) {
		if (module_matches_source(dependent_id)) {
			dependents.push(module_extract_path(dependent_id));
		}
	}

	// Sort for deterministic output
	dependencies.sort();
	dependents.sort();

	return {dependencies, dependents};
};
